// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgramacionIII.Data.Context;

#nullable disable

namespace ProgramacionIII.Migrations
{
    [DbContext(typeof(EcommerceContext))]
    partial class EcommerceContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("AdminProduct", b =>
                {
                    b.Property<int>("AdminsId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AdminsId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("AdminProduct");
                });

            modelBuilder.Entity("CustomerProduct", b =>
                {
                    b.Property<int>("CustomersId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CustomersId", "ProductsId");

                    b.HasIndex("ProductsId");

                    b.ToTable("CustomerProduct");
                });

            modelBuilder.Entity("ProgramacionIII.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Blanca",
                            Name = "Remera",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Negro",
                            Name = "Pantalon",
                            Price = 5000m
                        });
                });

            modelBuilder.Entity("ProgramacionIII.Data.Entities.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AdminId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("SalePrice")
                        .HasColumnType("REAL");

                    b.Property<int>("UseriId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ProductId");

                    b.ToTable("Sales");
                });

            modelBuilder.Entity("ProgramacionIII.Data.Entities.SaleOrderLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SaleOrderId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SaleOrderLines");
                });

            modelBuilder.Entity("ProgramacionIII.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasDiscriminator<string>("UserType").HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("ProgramacionIII.Data.Entities.Admin", b =>
                {
                    b.HasBaseType("ProgramacionIII.Data.Entities.User");

                    b.HasDiscriminator().HasValue("Admin");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Email = "morcapdevila457@gmail.com",
                            LastName = "Capdevila",
                            Name = "Mora",
                            Password = "12345678",
                            UserName = "moracapde"
                        },
                        new
                        {
                            Id = 4,
                            Email = "perezjuan@gmail.com",
                            LastName = "Perez",
                            Name = "Juan",
                            Password = "123456789",
                            UserName = "perez.juan"
                        });
                });

            modelBuilder.Entity("ProgramacionIII.Data.Entities.Customer", b =>
                {
                    b.HasBaseType("ProgramacionIII.Data.Entities.User");

                    b.HasDiscriminator().HasValue("Customer");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "juanitasan@gmail.com",
                            LastName = "Sanchez",
                            Name = "Juana",
                            Password = "123456",
                            UserName = "juana_san"
                        },
                        new
                        {
                            Id = 2,
                            Email = "lopeztomas@gmail.com",
                            LastName = "Lopez",
                            Name = "Tomas",
                            Password = "1234567",
                            UserName = "tomi_lopez"
                        });
                });

            modelBuilder.Entity("AdminProduct", b =>
                {
                    b.HasOne("ProgramacionIII.Data.Entities.Admin", null)
                        .WithMany()
                        .HasForeignKey("AdminsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgramacionIII.Data.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CustomerProduct", b =>
                {
                    b.HasOne("ProgramacionIII.Data.Entities.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProgramacionIII.Data.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProgramacionIII.Data.Entities.Sale", b =>
                {
                    b.HasOne("ProgramacionIII.Data.Entities.Admin", null)
                        .WithMany("Sale")
                        .HasForeignKey("AdminId");

                    b.HasOne("ProgramacionIII.Data.Entities.Customer", null)
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId");

                    b.HasOne("ProgramacionIII.Data.Entities.Product", null)
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ProgramacionIII.Data.Entities.Product", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("ProgramacionIII.Data.Entities.Admin", b =>
                {
                    b.Navigation("Sale");
                });

            modelBuilder.Entity("ProgramacionIII.Data.Entities.Customer", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
